services:
  # 1. PYTHON BACKEND (iz mape backend)
  disk-ml-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: diskBackend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - disk-network

  # 2. REACT FRONTEND (iz mape frontend)
  disk-ml-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: diskFrontend
    ports:
      - "3000:80"
    networks:
      - disk-network
    depends_on:
      - disk-ml-backend

networks:
  disk-network:
    driver: bridge