services:
  # 1. STREAMLIT APP (iz mape LLMApp)
  disk-ai-chat:
    build:
      context: .
      dockerfile: LLMApp/Dockerfile
    container_name: diskML
    ports:
      - "8501:8501"
    networks:
      - disk-network

  # 2. REACT FRONTEND (iz mape react)
  disk-react-frontend:
    build:
      context: .
      dockerfile: react/Dockerfile
    container_name: diskFrontend
    ports:
      - "3000:80"
    networks:
      - disk-network

networks:
  disk-network:
    driver: bridge